// @generated by frontend/scripts/build-frontend.mjs
const FRONTEND_INTEGRITY_FILES: &[FrontendIntegrityFile] = &[
    FrontendIntegrityFile {
        path: "index.html",
        sha256: "5277d277293ac07fddd87a554479a280a4b77d05b16a69d4d5c556dead14bb7c",
        bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../dist/index.html")),
    },
    FrontendIntegrityFile {
        path: "main.js",
        sha256: "9b0779de1174ad29b43e49fd6789af582bb18e203cfa365d903e0e37ca12e99e",
        bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../dist/main.js")),
    },
    FrontendIntegrityFile {
        path: "asr.js",
        sha256: "05856a14c7ea3aa52185eb2481f07017a516c1af2bedb9e7c76b85b207d193d0",
        bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../dist/asr.js")),
    },
    FrontendIntegrityFile {
        path: "styles.css",
        sha256: "4a1c81163b4fabaf0f41413573dfe76d82e9f04400544c494c54bf2c160f5fb6",
        bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../dist/styles.css")),
    },
    FrontendIntegrityFile {
        path: "assets/sf-arabic-regular.ttf",
        sha256: "d99abb8d697bde2bb8feab62873778870335dae7995e1ec94ce66142044b4f6d",
        bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../dist/assets/sf-arabic-regular.ttf")),
    }
];
